"""Competition package init."""
from .competition_settings import TASK_ALLOWED_CLASSES, TASK_MARGIN_THRESHOLDS, COMPATIBILITY_PENALTY, DEMO_MANIFEST

__all__ = ["TASK_ALLOWED_CLASSES", "TASK_MARGIN_THRESHOLDS", "COMPATIBILITY_PENALTY", "DEMO_MANIFEST"]
