"""Competition-mode settings: curated task mappings, thresholds, and demo manifests.
This file is intended to be edited by hand for competition tuning.
"""
from pathlib import Path

# Stronger, competition-oriented allowed classes per task (COCO names)
TASK_ALLOWED_CLASSES = {
    0: ["chair", "dining table", "bench"],
    1: ["chair", "couch", "dining table"],
    2: ["vase", "dining table", "potted plant"],
    3: ["fork", "spoon", "knife"],
    4: ["bottle", "cup", "bowl", "sink", "vase"],
    5: ["cup", "spoon", "fork", "bowl"],
    6: ["fork", "spoon", "knife"],
    7: ["bottle", "wine glass", "cup"],
    8: ["scissors", "knife", "book"],
    9: ["wine glass", "bottle", "cup"],
    10: ["spoon", "bowl", "cup", "bottle"],
    11: ["knife", "spoon", "fork"],
    12: ["fire hydrant", "bottle", "cup", "bowl", "sink"],
    13: ["baseball bat", "tennis racket", "skateboard"]
}

# Per-task margin thresholds tuned for competition (higher => more conservative)
TASK_MARGIN_THRESHOLDS = {
    0: 0.10,
    1: 0.12,
    2: 0.08,
    3: 0.10,
    4: 0.08,
    5: 0.06,
    6: 0.05,
    7: 0.07,
    8: 0.06,
    9: 0.07,
    10: 0.06,
    11: 0.05,
    12: 0.10,
    13: 0.08,
}

# Aggressive compatibility penalty multiplier for incompatible classes (0-1)
# Lower values strongly suppress incompatible detections.
COMPATIBILITY_PENALTY = 0.001

# Demo manifest placeholder (auto-generated by curation script)
DEMO_MANIFEST = Path(__file__).resolve().parent / 'demo_manifest.json'

def get_allowed(task_id):
    return TASK_ALLOWED_CLASSES.get(task_id, [])

def get_threshold(task_id):
    return TASK_MARGIN_THRESHOLDS.get(task_id, 0.08)
