// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ranking_mlp_top_ranking_mlp_top_Pipeline_fc3_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        h2,
        h2_1,
        h2_2,
        h2_3,
        h2_4,
        h2_5,
        h2_6,
        h2_7,
        h2_8,
        h2_9,
        h2_10,
        h2_11,
        h2_12,
        h2_13,
        h2_14,
        h2_15,
        h2_16,
        h2_17,
        h2_18,
        h2_19,
        h2_20,
        h2_21,
        h2_22,
        h2_23,
        h2_24,
        h2_25,
        h2_26,
        h2_27,
        h2_28,
        h2_29,
        h2_30,
        h2_31,
        h2_32,
        h2_33,
        h2_34,
        h2_35,
        h2_36,
        h2_37,
        h2_38,
        h2_39,
        h2_40,
        h2_41,
        h2_42,
        h2_43,
        h2_44,
        h2_45,
        h2_46,
        h2_47,
        h2_48,
        h2_49,
        h2_50,
        h2_51,
        h2_52,
        h2_53,
        h2_54,
        h2_55,
        h2_56,
        h2_57,
        h2_58,
        h2_59,
        h2_60,
        h2_61,
        h2_62,
        h2_63,
        score_out,
        score_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] h2;
input  [15:0] h2_1;
input  [15:0] h2_2;
input  [15:0] h2_3;
input  [15:0] h2_4;
input  [15:0] h2_5;
input  [15:0] h2_6;
input  [15:0] h2_7;
input  [15:0] h2_8;
input  [15:0] h2_9;
input  [15:0] h2_10;
input  [15:0] h2_11;
input  [15:0] h2_12;
input  [15:0] h2_13;
input  [15:0] h2_14;
input  [15:0] h2_15;
input  [15:0] h2_16;
input  [15:0] h2_17;
input  [15:0] h2_18;
input  [15:0] h2_19;
input  [15:0] h2_20;
input  [15:0] h2_21;
input  [15:0] h2_22;
input  [15:0] h2_23;
input  [15:0] h2_24;
input  [15:0] h2_25;
input  [15:0] h2_26;
input  [15:0] h2_27;
input  [15:0] h2_28;
input  [15:0] h2_29;
input  [15:0] h2_30;
input  [15:0] h2_31;
input  [15:0] h2_32;
input  [15:0] h2_33;
input  [15:0] h2_34;
input  [15:0] h2_35;
input  [15:0] h2_36;
input  [15:0] h2_37;
input  [15:0] h2_38;
input  [15:0] h2_39;
input  [15:0] h2_40;
input  [15:0] h2_41;
input  [15:0] h2_42;
input  [15:0] h2_43;
input  [15:0] h2_44;
input  [15:0] h2_45;
input  [15:0] h2_46;
input  [15:0] h2_47;
input  [15:0] h2_48;
input  [15:0] h2_49;
input  [15:0] h2_50;
input  [15:0] h2_51;
input  [15:0] h2_52;
input  [15:0] h2_53;
input  [15:0] h2_54;
input  [15:0] h2_55;
input  [15:0] h2_56;
input  [15:0] h2_57;
input  [15:0] h2_58;
input  [15:0] h2_59;
input  [15:0] h2_60;
input  [15:0] h2_61;
input  [15:0] h2_62;
input  [15:0] h2_63;
output  [15:0] score_out;
output   score_out_ap_vld;

reg ap_idle;
reg score_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_741_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln119_reg_1388;
reg   [0:0] icmp_ln119_reg_1388_pp0_iter1_reg;
reg   [15:0] score_fu_320;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [23:0] out_acc_fu_324;
reg   [23:0] ap_sig_allocacmp_out_acc_load;
reg   [6:0] j_fu_328;
wire   [6:0] add_ln119_fu_747_p2;
reg   [6:0] ap_sig_allocacmp_j_1;
wire    ap_block_pp0_stage0_01001;
wire   [5:0] tmp_2_fu_757_p129;
wire   [5:0] trunc_ln119_fu_753_p1;
wire   [5:0] tmp_2_fu_757_p131;
wire   [15:0] tmp_3_fu_1029_p129;
wire   [15:0] tmp_3_fu_1029_p131;
wire  signed [13:0] shl_ln2_fu_1021_p3;
wire  signed [19:0] shl_ln121_1_fu_1293_p3;
wire  signed [37:0] grp_fu_1357_p3;
wire  signed [37:0] grp_fu_1357_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [5:0] tmp_2_fu_757_p1;
wire   [5:0] tmp_2_fu_757_p3;
wire   [5:0] tmp_2_fu_757_p5;
wire   [5:0] tmp_2_fu_757_p7;
wire   [5:0] tmp_2_fu_757_p9;
wire   [5:0] tmp_2_fu_757_p11;
wire   [5:0] tmp_2_fu_757_p13;
wire   [5:0] tmp_2_fu_757_p15;
wire   [5:0] tmp_2_fu_757_p17;
wire   [5:0] tmp_2_fu_757_p19;
wire   [5:0] tmp_2_fu_757_p21;
wire   [5:0] tmp_2_fu_757_p23;
wire   [5:0] tmp_2_fu_757_p25;
wire   [5:0] tmp_2_fu_757_p27;
wire   [5:0] tmp_2_fu_757_p29;
wire   [5:0] tmp_2_fu_757_p31;
wire   [5:0] tmp_2_fu_757_p33;
wire   [5:0] tmp_2_fu_757_p35;
wire   [5:0] tmp_2_fu_757_p37;
wire   [5:0] tmp_2_fu_757_p39;
wire   [5:0] tmp_2_fu_757_p41;
wire   [5:0] tmp_2_fu_757_p43;
wire   [5:0] tmp_2_fu_757_p45;
wire   [5:0] tmp_2_fu_757_p47;
wire   [5:0] tmp_2_fu_757_p49;
wire   [5:0] tmp_2_fu_757_p51;
wire   [5:0] tmp_2_fu_757_p53;
wire   [5:0] tmp_2_fu_757_p55;
wire   [5:0] tmp_2_fu_757_p57;
wire   [5:0] tmp_2_fu_757_p59;
wire   [5:0] tmp_2_fu_757_p61;
wire   [5:0] tmp_2_fu_757_p63;
wire  signed [5:0] tmp_2_fu_757_p65;
wire  signed [5:0] tmp_2_fu_757_p67;
wire  signed [5:0] tmp_2_fu_757_p69;
wire  signed [5:0] tmp_2_fu_757_p71;
wire  signed [5:0] tmp_2_fu_757_p73;
wire  signed [5:0] tmp_2_fu_757_p75;
wire  signed [5:0] tmp_2_fu_757_p77;
wire  signed [5:0] tmp_2_fu_757_p79;
wire  signed [5:0] tmp_2_fu_757_p81;
wire  signed [5:0] tmp_2_fu_757_p83;
wire  signed [5:0] tmp_2_fu_757_p85;
wire  signed [5:0] tmp_2_fu_757_p87;
wire  signed [5:0] tmp_2_fu_757_p89;
wire  signed [5:0] tmp_2_fu_757_p91;
wire  signed [5:0] tmp_2_fu_757_p93;
wire  signed [5:0] tmp_2_fu_757_p95;
wire  signed [5:0] tmp_2_fu_757_p97;
wire  signed [5:0] tmp_2_fu_757_p99;
wire  signed [5:0] tmp_2_fu_757_p101;
wire  signed [5:0] tmp_2_fu_757_p103;
wire  signed [5:0] tmp_2_fu_757_p105;
wire  signed [5:0] tmp_2_fu_757_p107;
wire  signed [5:0] tmp_2_fu_757_p109;
wire  signed [5:0] tmp_2_fu_757_p111;
wire  signed [5:0] tmp_2_fu_757_p113;
wire  signed [5:0] tmp_2_fu_757_p115;
wire  signed [5:0] tmp_2_fu_757_p117;
wire  signed [5:0] tmp_2_fu_757_p119;
wire  signed [5:0] tmp_2_fu_757_p121;
wire  signed [5:0] tmp_2_fu_757_p123;
wire  signed [5:0] tmp_2_fu_757_p125;
wire  signed [5:0] tmp_2_fu_757_p127;
wire   [5:0] tmp_3_fu_1029_p1;
wire   [5:0] tmp_3_fu_1029_p3;
wire   [5:0] tmp_3_fu_1029_p5;
wire   [5:0] tmp_3_fu_1029_p7;
wire   [5:0] tmp_3_fu_1029_p9;
wire   [5:0] tmp_3_fu_1029_p11;
wire   [5:0] tmp_3_fu_1029_p13;
wire   [5:0] tmp_3_fu_1029_p15;
wire   [5:0] tmp_3_fu_1029_p17;
wire   [5:0] tmp_3_fu_1029_p19;
wire   [5:0] tmp_3_fu_1029_p21;
wire   [5:0] tmp_3_fu_1029_p23;
wire   [5:0] tmp_3_fu_1029_p25;
wire   [5:0] tmp_3_fu_1029_p27;
wire   [5:0] tmp_3_fu_1029_p29;
wire   [5:0] tmp_3_fu_1029_p31;
wire   [5:0] tmp_3_fu_1029_p33;
wire   [5:0] tmp_3_fu_1029_p35;
wire   [5:0] tmp_3_fu_1029_p37;
wire   [5:0] tmp_3_fu_1029_p39;
wire   [5:0] tmp_3_fu_1029_p41;
wire   [5:0] tmp_3_fu_1029_p43;
wire   [5:0] tmp_3_fu_1029_p45;
wire   [5:0] tmp_3_fu_1029_p47;
wire   [5:0] tmp_3_fu_1029_p49;
wire   [5:0] tmp_3_fu_1029_p51;
wire   [5:0] tmp_3_fu_1029_p53;
wire   [5:0] tmp_3_fu_1029_p55;
wire   [5:0] tmp_3_fu_1029_p57;
wire   [5:0] tmp_3_fu_1029_p59;
wire   [5:0] tmp_3_fu_1029_p61;
wire   [5:0] tmp_3_fu_1029_p63;
wire  signed [5:0] tmp_3_fu_1029_p65;
wire  signed [5:0] tmp_3_fu_1029_p67;
wire  signed [5:0] tmp_3_fu_1029_p69;
wire  signed [5:0] tmp_3_fu_1029_p71;
wire  signed [5:0] tmp_3_fu_1029_p73;
wire  signed [5:0] tmp_3_fu_1029_p75;
wire  signed [5:0] tmp_3_fu_1029_p77;
wire  signed [5:0] tmp_3_fu_1029_p79;
wire  signed [5:0] tmp_3_fu_1029_p81;
wire  signed [5:0] tmp_3_fu_1029_p83;
wire  signed [5:0] tmp_3_fu_1029_p85;
wire  signed [5:0] tmp_3_fu_1029_p87;
wire  signed [5:0] tmp_3_fu_1029_p89;
wire  signed [5:0] tmp_3_fu_1029_p91;
wire  signed [5:0] tmp_3_fu_1029_p93;
wire  signed [5:0] tmp_3_fu_1029_p95;
wire  signed [5:0] tmp_3_fu_1029_p97;
wire  signed [5:0] tmp_3_fu_1029_p99;
wire  signed [5:0] tmp_3_fu_1029_p101;
wire  signed [5:0] tmp_3_fu_1029_p103;
wire  signed [5:0] tmp_3_fu_1029_p105;
wire  signed [5:0] tmp_3_fu_1029_p107;
wire  signed [5:0] tmp_3_fu_1029_p109;
wire  signed [5:0] tmp_3_fu_1029_p111;
wire  signed [5:0] tmp_3_fu_1029_p113;
wire  signed [5:0] tmp_3_fu_1029_p115;
wire  signed [5:0] tmp_3_fu_1029_p117;
wire  signed [5:0] tmp_3_fu_1029_p119;
wire  signed [5:0] tmp_3_fu_1029_p121;
wire  signed [5:0] tmp_3_fu_1029_p123;
wire  signed [5:0] tmp_3_fu_1029_p125;
wire  signed [5:0] tmp_3_fu_1029_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 score_fu_320 = 16'd0;
#0 out_acc_fu_324 = 24'd0;
#0 j_fu_328 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) ranking_mlp_top_sparsemux_129_6_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 6 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 6 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 6 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 6 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 6 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 6 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 6 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 6 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 6 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 6 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 6 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 6 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 6 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 6 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 6 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 6 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 6 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 6 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 6 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 6 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 6 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 6 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 6 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 6 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 6 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 6 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 6 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 6 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 6 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 6 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 6 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 6 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 6 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 6 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 6 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 6 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 6 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 6 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 6 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 6 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 6 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 6 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 6 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 6 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 6 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 6 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 6 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 6 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 6 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 6 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 6 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 6 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 6 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 6 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 6 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 6 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 6 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 6 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 6 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 6 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 6 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 6 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 6 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 6 ),
    .def_WIDTH( 6 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 6 ))
sparsemux_129_6_6_1_1_U731(
    .din0(6'd8),
    .din1(6'd54),
    .din2(6'd55),
    .din3(6'd58),
    .din4(6'd6),
    .din5(6'd0),
    .din6(6'd3),
    .din7(6'd15),
    .din8(6'd12),
    .din9(6'd13),
    .din10(6'd5),
    .din11(6'd9),
    .din12(6'd59),
    .din13(6'd13),
    .din14(6'd59),
    .din15(6'd59),
    .din16(6'd2),
    .din17(6'd59),
    .din18(6'd15),
    .din19(6'd54),
    .din20(6'd0),
    .din21(6'd8),
    .din22(6'd14),
    .din23(6'd62),
    .din24(6'd55),
    .din25(6'd16),
    .din26(6'd59),
    .din27(6'd6),
    .din28(6'd62),
    .din29(6'd10),
    .din30(6'd13),
    .din31(6'd44),
    .din32(6'd59),
    .din33(6'd58),
    .din34(6'd11),
    .din35(6'd57),
    .din36(6'd24),
    .din37(6'd12),
    .din38(6'd58),
    .din39(6'd62),
    .din40(6'd13),
    .din41(6'd56),
    .din42(6'd56),
    .din43(6'd63),
    .din44(6'd0),
    .din45(6'd54),
    .din46(6'd8),
    .din47(6'd62),
    .din48(6'd57),
    .din49(6'd58),
    .din50(6'd62),
    .din51(6'd60),
    .din52(6'd11),
    .din53(6'd61),
    .din54(6'd10),
    .din55(6'd57),
    .din56(6'd6),
    .din57(6'd54),
    .din58(6'd57),
    .din59(6'd59),
    .din60(6'd58),
    .din61(6'd13),
    .din62(6'd20),
    .din63(6'd14),
    .def(tmp_2_fu_757_p129),
    .sel(trunc_ln119_fu_753_p1),
    .dout(tmp_2_fu_757_p131)
);

(* dissolve_hierarchy = "yes" *) ranking_mlp_top_sparsemux_129_6_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 16 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 16 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 16 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 16 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 16 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 16 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 16 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 16 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 16 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 16 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 16 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 16 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 16 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 16 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 16 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 16 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 16 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 16 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 16 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 16 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 16 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 16 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 16 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 16 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 16 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 16 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 16 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 16 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 16 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 16 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 16 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 16 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
sparsemux_129_6_16_1_1_U732(
    .din0(h2),
    .din1(h2_1),
    .din2(h2_2),
    .din3(h2_3),
    .din4(h2_4),
    .din5(h2_5),
    .din6(h2_6),
    .din7(h2_7),
    .din8(h2_8),
    .din9(h2_9),
    .din10(h2_10),
    .din11(h2_11),
    .din12(h2_12),
    .din13(h2_13),
    .din14(h2_14),
    .din15(h2_15),
    .din16(h2_16),
    .din17(h2_17),
    .din18(h2_18),
    .din19(h2_19),
    .din20(h2_20),
    .din21(h2_21),
    .din22(h2_22),
    .din23(h2_23),
    .din24(h2_24),
    .din25(h2_25),
    .din26(h2_26),
    .din27(h2_27),
    .din28(h2_28),
    .din29(h2_29),
    .din30(h2_30),
    .din31(h2_31),
    .din32(h2_32),
    .din33(h2_33),
    .din34(h2_34),
    .din35(h2_35),
    .din36(h2_36),
    .din37(h2_37),
    .din38(h2_38),
    .din39(h2_39),
    .din40(h2_40),
    .din41(h2_41),
    .din42(h2_42),
    .din43(h2_43),
    .din44(h2_44),
    .din45(h2_45),
    .din46(h2_46),
    .din47(h2_47),
    .din48(h2_48),
    .din49(h2_49),
    .din50(h2_50),
    .din51(h2_51),
    .din52(h2_52),
    .din53(h2_53),
    .din54(h2_54),
    .din55(h2_55),
    .din56(h2_56),
    .din57(h2_57),
    .din58(h2_58),
    .din59(h2_59),
    .din60(h2_60),
    .din61(h2_61),
    .din62(h2_62),
    .din63(h2_63),
    .def(tmp_3_fu_1029_p129),
    .sel(trunc_ln119_fu_753_p1),
    .dout(tmp_3_fu_1029_p131)
);

ranking_mlp_top_mac_muladd_20s_14s_38s_38_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 38 ),
    .dout_WIDTH( 38 ))
mac_muladd_20s_14s_38s_38_4_1_U733(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(shl_ln121_1_fu_1293_p3),
    .din1(shl_ln2_fu_1021_p3),
    .din2(grp_fu_1357_p2),
    .ce(1'b1),
    .dout(grp_fu_1357_p3)
);

ranking_mlp_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_741_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_328 <= add_ln119_fu_747_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_328 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            out_acc_fu_324 <= 24'd16775104;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            out_acc_fu_324 <= {{grp_fu_1357_p3[37:14]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            score_fu_320 <= 16'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            score_fu_320 <= {{grp_fu_1357_p3[33:18]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln119_reg_1388 <= icmp_ln119_fu_741_p2;
        icmp_ln119_reg_1388_pp0_iter1_reg <= icmp_ln119_reg_1388;
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_741_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_328;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_out_acc_load = {{grp_fu_1357_p3[37:14]}};
    end else begin
        ap_sig_allocacmp_out_acc_load = out_acc_fu_324;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln119_reg_1388_pp0_iter1_reg == 1'd1))) begin
        score_out_ap_vld = 1'b1;
    end else begin
        score_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_fu_747_p2 = (ap_sig_allocacmp_j_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_1357_p2 = {{ap_sig_allocacmp_out_acc_load}, {14'd0}};

assign icmp_ln119_fu_741_p2 = ((ap_sig_allocacmp_j_1 == 7'd64) ? 1'b1 : 1'b0);

assign score_out = score_fu_320;

assign shl_ln121_1_fu_1293_p3 = {{tmp_3_fu_1029_p131}, {4'd0}};

assign shl_ln2_fu_1021_p3 = {{tmp_2_fu_757_p131}, {8'd0}};

assign tmp_2_fu_757_p129 = 'bx;

assign tmp_3_fu_1029_p129 = 'bx;

assign trunc_ln119_fu_753_p1 = ap_sig_allocacmp_j_1[5:0];

endmodule //ranking_mlp_top_ranking_mlp_top_Pipeline_fc3_loop
