"""
Export trained RankingMLP weights to Vitis HLS ROM header.

Input checkpoint format:
- state_dict with keys: fc1.weight, fc1.bias, fc2.weight, fc2.bias

Output:
- fpga/hls/ranking_mlp/weights.h

Per-layer dynamic fixed-point quantization is applied to maximise weight
precision within the ap_fixed<8,2> representation.  Each layer's weights and
biases are divided by a per-layer scale factor so that the largest magnitude
value fills the representable range [-2.0, +1.984375].  The scale factors are
stored as float constants in the header so the host can reconstruct true logit
values via:  score_true = score_fpga_dequant * fc1_scale * fc2_scale

Usage:
  py scripts/export_hls_weights.py --ckpt checkpoints/ranker_best.pt
"""

import argparse
import os

import torch

IN_DIM = 731
HID_DIM = 128
Q_MAX = 1.984375   # ap_fixed<8,2> positive max
Q_MIN = -2.0       # ap_fixed<8,2> negative min
Q_STEP = 1.0 / 64  # ap_fixed<8,2> LSB (6 fractional bits)


def _per_layer_scale(tensors) -> float:
    """
    Compute scale factor so that after dividing by scale, the largest-magnitude
    value exactly fills the ap_fixed<8,2> representable range.

    Returns 1.0 if all values are zero or negligibly small.
    """
    max_abs = max(t.abs().max().item() for t in tensors)
    if max_abs < 1e-9:
        return 1.0
    return max_abs / Q_MAX


def _quantize(x: float, scale: float) -> tuple:
    """
    Apply per-layer scaling then quantize to ap_fixed<8,2>.

    Returns (literal_str, was_clamped).
    """
    xs = x / scale                        # fills the representable range
    q = round(xs / Q_STEP) * Q_STEP      # round to nearest LSB
    clamped = False
    if q < Q_MIN:
        q = Q_MIN
        clamped = True
    if q > Q_MAX:
        q = Q_MAX
        clamped = True
    return f"{q:.6f}", clamped


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt", required=True, help="Path to .pt checkpoint")
    parser.add_argument(
        "--out",
        default="fpga/hls/ranking_mlp/weights.h",
        help="Output header path",
    )
    args = parser.parse_args()

    sd = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    if "model" in sd:
        sd = sd["model"]

    fc1_w = sd["fc1.weight"].detach().cpu()  # [128, 731]
    fc1_b = sd["fc1.bias"].detach().cpu()    # [128]
    fc2_w = sd["fc2.weight"].detach().cpu()  # [1, 128]
    fc2_b = sd["fc2.bias"].detach().cpu()    # [1]

    if tuple(fc1_w.shape) != (HID_DIM, IN_DIM):
        raise ValueError(f"Unexpected fc1.weight shape: {tuple(fc1_w.shape)}")
    if tuple(fc1_b.shape) != (HID_DIM,):
        raise ValueError(f"Unexpected fc1.bias shape: {tuple(fc1_b.shape)}")
    if tuple(fc2_w.shape) != (1, HID_DIM):
        raise ValueError(f"Unexpected fc2.weight shape: {tuple(fc2_w.shape)}")
    if tuple(fc2_b.shape) != (1,):
        raise ValueError(f"Unexpected fc2.bias shape: {tuple(fc2_b.shape)}")

    # Per-layer dynamic fixed-point scale factors.
    # Weights and biases for the same layer share one scale so the affine
    # transform is internally consistent: true_output = scale * fpga_output.
    fc1_scale = _per_layer_scale([fc1_w, fc1_b])
    fc2_scale = _per_layer_scale([fc2_w, fc2_b])

    # Diagnostic: show utilisation of representable range before/after scaling
    fc1_max_abs_orig = max(fc1_w.abs().max().item(), fc1_b.abs().max().item())
    fc2_max_abs_orig = max(fc2_w.abs().max().item(), fc2_b.abs().max().item())
    print(f"FC1 weight range before scaling: [{fc1_w.min().item():.4f}, {fc1_w.max().item():.4f}]")
    print(f"FC2 weight range before scaling: [{fc2_w.min().item():.4f}, {fc2_w.max().item():.4f}]")
    print(f"FC1 scale factor: {fc1_scale:.6f}  "
          f"(range utilisation before: {fc1_max_abs_orig/Q_MAX*100:.1f}%)")
    print(f"FC2 scale factor: {fc2_scale:.6f}  "
          f"(range utilisation before: {fc2_max_abs_orig/Q_MAX*100:.1f}%)")

    lines = []
    lines.append("#ifndef RANKING_MLP_WEIGHTS_H")
    lines.append("#define RANKING_MLP_WEIGHTS_H")
    lines.append("")
    lines.append("#include \"top.h\"")
    lines.append("")
    lines.append("// Auto-generated by scripts/export_hls_weights.py")
    lines.append("//")
    lines.append("// Per-layer dynamic fixed-point quantization:")
    lines.append("//   weights and biases are divided by a per-layer scale factor")
    lines.append("//   so the largest magnitude value fills ap_fixed<8,2> range.")
    lines.append("//")
    lines.append("// To recover true logit from the FPGA integer output:")
    lines.append("//   score_true = (int16_out / 1024.0f) * FC1_SCALE * FC2_SCALE")
    lines.append(f"#define FC1_SCALE {fc1_scale:.8f}f")
    lines.append(f"#define FC2_SCALE {fc2_scale:.8f}f")
    lines.append("")

    clamp_count = 0

    lines.append("const weight_t fc1_w[HID_DIM][IN_DIM] = {")
    for i in range(HID_DIM):
        row_vals = []
        for j in range(IN_DIM):
            lit, clamped = _quantize(float(fc1_w[i, j]), fc1_scale)
            if clamped:
                clamp_count += 1
            row_vals.append(lit)
        row = ", ".join(row_vals)
        comma = "," if i != HID_DIM - 1 else ""
        lines.append("    {" + row + "}" + comma)
    lines.append("};")

    b1_vals = []
    for i in range(HID_DIM):
        lit, clamped = _quantize(float(fc1_b[i]), fc1_scale)
        if clamped:
            clamp_count += 1
        b1_vals.append(lit)
    lines.append("const weight_t fc1_b[HID_DIM] = {" + ", ".join(b1_vals) + "};")

    w2_vals = []
    for i in range(HID_DIM):
        lit, clamped = _quantize(float(fc2_w[0, i]), fc2_scale)
        if clamped:
            clamp_count += 1
        w2_vals.append(lit)
    lines.append("const weight_t fc2_w[HID_DIM] = {" + ", ".join(w2_vals) + "};")

    b2_lit, b2_clamped = _quantize(float(fc2_b[0]), fc2_scale)
    if b2_clamped:
        clamp_count += 1
    lines.append("const weight_t fc2_b = " + b2_lit + ";")
    lines.append("")
    lines.append("#endif")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nExported HLS weights to: {args.out}")
    if clamp_count > 0:
        print(f"Warning: {clamp_count} values clamped (scale factor may be too small)")
    else:
        print("All values quantised without clamping (full-range utilisation achieved)")


if __name__ == "__main__":
    main()

